describe("testharnas", function()
  it("draait onder Lua 5.1", function()
    assert.equals("Lua 5.1", _VERSION)
  end)

  it("heeft unpack als global en geen table.unpack", function()
    assert.equals("function", type(unpack))
    assert.is_nil(table.unpack)
  end)

  it("vergelijkt geneste tabellen en noemt het afwijkende pad", function()
    local ok, err = pcall(function()
      assert.same({ a = { b = 1 } }, { a = { b = 2 } })
    end)
    assert.falsy(ok)
    assert.matches("%.a%.b", err)
  end)

  it("laadt een module met de addon-namespace", function()
    local helper = dofile("spec/helper.lua")
    local ns = helper.loadModules({ "RaidInspector/Version.lua" })
    assert.equals("0.1.0", ns.VERSION)
  end)
end)
