local addonName, ns = ...

ns.Data = ns.Data or {}

-- GENERATED by tools/generate.mjs from build 12.1.0.69299. Do not edit by hand.
-- Class tier sets for the current season: item sets with exactly five
-- pieces whose members are in the current item ID block. PvP sets have
-- eight pieces and older sets have two or three, so they fall out.
ns.Data.TierSets = {
  [2055] = true,  -- Baleful Grave-Knight's Crucible
  [2056] = true,  -- Abyssal Doomhound's Pursuit
  [2057] = true,  -- Bark of the Enigmatic Dreamwatcher
  [2058] = true,  -- Echo of Calamity
  [2059] = true,  -- Skulking Viper's Ambush
  [2060] = true,  -- Primal Leywarden's Attire
  [2061] = true,  -- Guile of the Monkey King
  [2062] = true,  -- Radiance of the Consecrated Flame
  [2063] = true,  -- Cosmic Penitent's Raiment
  [2064] = true,  -- Chosen Bloodslayer's Hexweave
  [2065] = true,  -- Ophidian Oracle's Prophecy
  [2066] = true,  -- Damned Necrolyte's Shattered Restraints
  [2067] = true,  -- Jade Warlord's Dominion
}
