local addonName, ns = ...

ns.Data = ns.Data or {}

-- GENERATED by tools/generate.mjs from build 12.0.7.68887. Do not edit by hand.
-- Class tier sets for the current season: item sets with exactly five
-- pieces whose members are in the current item ID block. PvP sets have
-- eight pieces and older sets have two or three, so they fall out.
ns.Data.TierSets = {
  [1978] = true,  -- Relentless Rider's Lament
  [1979] = true,  -- Devouring Reaver's Sheathe
  [1980] = true,  -- Sprouts of the Luminous Bloom
  [1981] = true,  -- Livery of the Black Talon
  [1982] = true,  -- Primal Sentry's Camouflage
  [1983] = true,  -- Voidbreaker's Accordance
  [1984] = true,  -- Way of Ra-den's Chosen
  [1985] = true,  -- Luminant Verdict's Vestments
  [1986] = true,  -- Blind Oath's Burden
  [1987] = true,  -- Motley of the Grim Jest
  [1988] = true,  -- Mantle of the Primal Core
  [1989] = true,  -- Reign of the Abyssal Immolator
  [1990] = true,  -- Rage of the Night Ender
}
