local addonName, ns = ...

ns.Data = ns.Data or {}

-- GENERATED by tools/generate.mjs. Do not edit by hand.
-- DataVersion degrades on the patch version, never on the build number:
-- build numbers rise almost weekly through hotfixes that touch no items.
ns.Data.Version = {
  version = "12.1.0",
  build   = "69299",
}
